# =========================
# Netlify Configuration
# =========================

[build]
  command = "bun run build"
  publish = "dist"

# Proxy /api/* to your Google Apps Script
[[redirects]]
  from = "/api/*"
  to = "https://script.google.com/macros/s/AKfycbyXElaDXYk1Hkw2oXjx4s2IM2546FaBWW9Mhwoh7fShYPu3Mvkq0IWI1BKvJiv1bGA-XA/exec"
  status = 200
  force = true

#  Support Vue router (history mode)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
