# netlify.toml (Correct Version)

[build]
  command = "npm run build"
  publish = "dist"

# Proxy /api to your Google Apps Script
[[redirects]]
  from = "/api"
  to = "https://script.google.com/macros/s/AKfycbzA9uII3S4bndv-9dBx-JuUpc6s3zSwo_D6FaNdupDz-zVvufnGFd9sEiXKJ26MqgejHA/exec"
  status = 200
  force = true

# This rule for Vue Router MUST BE LAST
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200